# Generated by Django 5.0.14 on 2025-11-03 04:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('preferred_date', models.DateField(help_text="Customer's preferred travel date")),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Number of people must be at least 1'), django.core.validators.MaxValueValidator(1000, message='Number of people cannot exceed 1000')])),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requests or requirements', null=True)),
                ('inquiry_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use', null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_valid_until', models.DateField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_inquiries', to='dede.tour')),
            ],
            options={
                'verbose_name': 'Quote Inquiry',
                'verbose_name_plural': 'Quote Inquiries',
                'ordering': ['-inquiry_date'],
            },
        ),
    ]
