# Generated by Django 5.0.14 on 2025-12-15 12:48

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
