"""
Django settings for tours_travels project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

from dotenv import load_dotenv

load_dotenv()


EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent 
# Import all constants to use throughout our application
try:
    from ecommerce.constants import *
except ImportError:
    pass



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "seen"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Google OAuth settings
GOOGLE_CLIENT_ID = '876054945568-ma5924no5c16cetu6umbkanpsu3djppt.apps.googleusercontent.com'

# Security settings
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://127.0.0.1:8000',
    'https://localhost:8000'
]

# If you're using HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False  # Set to True in production
SESSION_COOKIE_SECURE = False  # Set to True only when using HTTPS in production
CSRF_COOKIE_SECURE = False  # Set to True only when using HTTPS in production

# Update your ALLOWED_HOSTS if needed
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']
# settings.py
# tours_travels/settings.py
GOOGLE_CLIENT_ID = '876054945568-ma5924no5c16cetu6umbkanpsu3djppt.apps.googleusercontent.com'

# Application definition

INSTALLED_APPS = [

    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'pyuploadcare.dj',
    'taggit',
    'crispy_forms',
    'django_ckeditor_5',

    'adminside',
    'users',
    'blog',
    'aronia',
    'events',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tours_travels.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'users.context_processors.google_client_id',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'tours_travels.wsgi.application'

# Database Configuration
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Production Database Safety Check
PRODUCTION_DB = config('PRODUCTION_DB', default=False, cast=bool)

if PRODUCTION_DB:
    print("⚠️  WARNING: Using PRODUCTION database! Be careful with migrations.")
# Primary database configuration using environment variables
DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    # Use DATABASE_URL if provided (recommended for production)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
    # Override connection settings for better performance and reliability
    DATABASES['default'].update({
        'CONN_MAX_AGE': 0,  # Disable connection persistence for safety
        'OPTIONS': {
            'client_encoding': 'UTF8',
            'application_name': 'django_aronia_travel',
            'sslmode': 'prefer',
        },
    })
else:
    # Fallback to individual environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='neondb'),
            'USER': config('DB_USER', default='neondb_owner'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='ep-shy-frog-a2opf8tj-pooler.eu-central-1.aws.neon.tech'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 0,  # Disable connection persistence
            'OPTIONS': {
                'client_encoding': 'UTF8',
                'application_name': 'django_aronia_travel',
                'sslmode': 'prefer',
            },
        }
    }
X_FRAME_OPTIONS = 'SAMEORIGIN'
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

SITE_ID = 1
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

CRISPY_TEMPLATE_PACK='bootstrap4'

LOGIN_REDIRECT_URL='aronia:home'
LOGIN_URL='login'
LOGOUT_REDIRECT_URL = 'aronia:home'

# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'users': {  # This will catch all loggers in the users app
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

## For media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media/')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

UPLOADCARE = {
  # Don't forget to set real keys when it gets real :)

  'pub_key': '21c2913d4e908096d38e', 
  'secret': 'e99a7668da1327823902',
}

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,  'templates'),
    # Add to this list all the locations containing your static files 
)



# Email Configuration - Mailtrap HTTP API
MAILTRAP_API_TOKEN = os.getenv('MAILTRAP_API_TOKEN', 'd766975d57a7ef1acf2f750a36247a37')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Novustell Travel <info@novustelltravel.com>')
ADMIN_EMAIL = 'info@aroniatravel.com'

# Email routing for different inquiry types
EMAIL_ROUTING = {
    'general': 'info@aroniatravel.com',
    'careers': 'careers@aroniatravel.com',
    'news': 'news@aroniatravel.com',
    'mice': 'info@aroniatravel.com',
    'booking': 'info@aroniatravel.com',
    'support': 'info@aroniatravel.com',
}

# Fallback to Gmail SMTP if Mailtrap token not available (for development)
if not MAILTRAP_API_TOKEN:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('GMAIL_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '')
# Django Jet settings
JET_DEFAULT_THEME = 'light-gray'
JET_DEFAULT_THEME = 'light-gray'
JET_THEMES = [
    {
        'theme': 'default',
        'color': '#47bac1',
        'title': 'Default'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]
JET_SIDE_MENU_COMPACT = True


# Disable Django Jet's select2 for better compatibility

# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', '|',
            'imageUpload', 'insertTable', '|',
            'outdent', 'indent', '|',
            'undo', 'redo'
        ],
        'height': 400,
        'width': '100%',
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:full', 'imageStyle:side'
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells'
            ]
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
            ]
        }
    },
    'blog': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'link', '|',
            'bulletedList', 'numberedList', 'blockQuote', 'codeBlock', '|',
            'imageUpload', 'insertTable', 'mediaEmbed', '|',
            'alignment', 'outdent', 'indent', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'removeFormat', 'undo', 'redo'
        ],
        'height': 500,
        'width': '100%',
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:full', 'imageStyle:side', 'imageStyle:alignLeft', 'imageStyle:alignRight'
            ],
            'styles': [
                'full', 'side', 'alignLeft', 'alignRight'
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'
            ]
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4'},
            ]
        },
        'fontSize': {
            'options': [9, 11, 13, 'default', 17, 19, 21]
        },
        'fontColor': {
            'colors': [
                {'color': 'hsl(0, 0%, 0%)', 'label': 'Black'},
                {'color': 'hsl(0, 0%, 30%)', 'label': 'Dim grey'},
                {'color': 'hsl(0, 0%, 60%)', 'label': 'Grey'},
                {'color': 'hsl(0, 0%, 90%)', 'label': 'Light grey'},
                {'color': 'hsl(0, 0%, 100%)', 'label': 'White', 'hasBorder': True},
                {'color': 'hsl(0, 75%, 60%)', 'label': 'Red'},
                {'color': 'hsl(30, 75%, 60%)', 'label': 'Orange'},
                {'color': 'hsl(60, 75%, 60%)', 'label': 'Yellow'},
                {'color': 'hsl(90, 75%, 60%)', 'label': 'Light green'},
                {'color': 'hsl(120, 75%, 60%)', 'label': 'Green'},
                {'color': 'hsl(150, 75%, 60%)', 'label': 'Aquamarine'},
                {'color': 'hsl(180, 75%, 60%)', 'label': 'Turquoise'},
                {'color': 'hsl(210, 75%, 60%)', 'label': 'Light blue'},
                {'color': 'hsl(240, 75%, 60%)', 'label': 'Blue'},
                {'color': 'hsl(270, 75%, 60%)', 'label': 'Purple'},
            ]
        }
    }
}

# CKEditor 5 file upload settings
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.default_storage"
JET_SELECT2_THEME = None
