# Generated by Django 5.0.14 on 2025-11-03 03:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Brief description of the post (optional)', null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
